package com.grailslab.myapp.config

class ConfigKey {
    public static final String STARTUP_UPSCRIPT_ENABLED = "startup.upscript.enabled"
    public static final String GLOBAL_DATABASE_DRIVER = "global.database.driver"
    public static final String GLOBAL_STORAGE_CONFIG = "global.storage.config"
    public static final String AES_ENCRYPTION_KEY = "aes.encryption.key"
    public static final String STORAGE_CONNECTION_STRING = "azure.storage.connection.string"
    public static final String FILE_STORAGE_PATH = "file.storage.path"
    public static final String DATASOURCE_URL = "dataSource.url"
    public static final String DATASOURCE_USERNAME = "dataSource.username"
    public static final String DATASOURCE_PASSWORD = "dataSource.password"
    public static final String SMS_SEND_ENABLED = "powersms.send.enabled"
    public static final String EAS_NOTIFICATION_SMS = "eas.deduct.notification.sms"
    public static final String SMS_API_USERID = "powersms.api.userid"
    public static final String SMS_API_PASSWORD = "powersms.api.password"
    public static final String MY_SMS_API_USERID = "mysms.api.userid"
    public static final String MY_SMS_API_PASSWORD = "mysms.api.password"
    public static final String SMS_SENDER_NUMBER = "bulksms.sender.number"
    public static final String SMS_BALANCE_REQUEST_NUM = "bulksms.balance.request.number"
    public static final String AMAR_UDDOG_NON_MASKING_NUM = "amaruddog.nonmasking.number"
    public static final String AMAR_UDDOG_SOFTWARE_MARKETBY = "amaruddog.software.marketby"
    public static final String GRAILSLAP_GSCHOOL_RUNNING = "grailslab.gschool.running"
    public static final String GRAILSLAP_GSCHOOL_WEEKLY_HOLIDAY = "grailslab.gschool.weekly.holiday"
    public static final String GRAILSLAP_GSCHOOL_ATTN_CALC = "grailslab.gschool.attendance.calculation"
    public static final String GRAILSLAP_GSCHOOL_STD_MORNING_IN = "grailslab.gschool.morning.inTime"
    public static final String GRAILSLAP_GSCHOOL_STD_DAY_IN = "grailslab.gschool.day.inTime"
    public static final String GRAILSLAP_GSCHOOL_TEA_MORNING_IN = "grailslab.gschool.teacher.morning.inTime"
    public static final String GRAILSLAP_GSCHOOL_TEA_DAY_IN = "grailslab.gschool.teacher.day.inTime"
    public static final String GRAILSLAP_GSCHOOL_IMAGE_PATH = "app.uploads.images.filesystemPath"
    public static final String GRAILSLAP_GSCHOOL_FILE_PATH = "app.uploads.files.filesystemPath"
    public static final String GRAILSLAP_GSCHOOL_SENT_FROM = "powersms.send.from.text"

    public static final String SPRING_REST_USERNAME_KEY = "grails.plugin.springsecurity.rest.login.usernamePropertyName"
    public static final String SPRING_REST_PASSWORD_KEY = "grails.plugin.springsecurity.rest.login.passwordPropertyName"
    public static final String EXPIRE_TIME = "global.tempPassword.expiredTime"
    public static final String FORGET_PASSWORD_LOCK_TIME = "global.forget.password.lockTime"
    public static final String MOBILE_VERSION_CODE = "mobile.apps.version"
}
