package com.grailslab

/**
 * Created by aminul on 11/7/2014.
 */
class ParamDetailReference {
    String param0Name
    String param1Name
    String param2Name
    String param3Name
    String param4Name
    String param5Name
    String param6Name
    String param7Name
    String param8Name
    String param9Name
    String param10Name
    String param11Name
    String param12Name
    String param13Name
    String param14Name
    String param15Name
    String param16Name
    String param17Name
    String param18Name
    String param19Name
    String param20Name
    String param21Name
    String param22Name
    String param23Name
    String param24Name
    String param25Name
    String param26Name
    String param27Name
    String param28Name

    Integer subject0ct
    Integer subject1ct
    Integer subject2ct
    Integer subject3ct
    Integer subject4ct
    Integer subject5ct
    Integer subject6ct
    Integer subject7ct
    Integer subject8ct
    Integer subject9ct
    Integer subject10ct
    Integer subject11ct
    Integer subject12ct
    Integer subject13ct
    Integer subject14ct
    Integer subject15ct
    Integer subject16ct
    Integer subject17ct
    Integer subject18ct
    Integer subject19ct
    Integer subject20ct
    Integer subject21ct
    Integer subject22ct
    Integer subject23ct
    Integer subject24ct
    Integer subject25ct
    Integer subject26ct
    Integer subject27ct
    Integer subject28ct

    Integer subject0ctEff
    Integer subject1ctEff
    Integer subject2ctEff
    Integer subject3ctEff
    Integer subject4ctEff
    Integer subject5ctEff
    Integer subject6ctEff
    Integer subject7ctEff
    Integer subject8ctEff
    Integer subject9ctEff
    Integer subject10ctEff
    Integer subject11ctEff
    Integer subject12ctEff
    Integer subject13ctEff
    Integer subject14ctEff
    Integer subject15ctEff
    Integer subject16ctEff
    Integer subject17ctEff
    Integer subject18ctEff
    Integer subject19ctEff
    Integer subject20ctEff
    Integer subject21ctEff
    Integer subject22ctEff
    Integer subject23ctEff
    Integer subject24ctEff
    Integer subject25ctEff
    Integer subject26ctEff
    Integer subject27ctEff
    Integer subject28ctEff

    Integer subject0hallWri
    Integer subject1hallWri
    Integer subject2hallWri
    Integer subject3hallWri
    Integer subject4hallWri
    Integer subject5hallWri
    Integer subject6hallWri
    Integer subject7hallWri
    Integer subject8hallWri
    Integer subject9hallWri
    Integer subject10hallWri
    Integer subject11hallWri
    Integer subject12hallWri
    Integer subject13hallWri
    Integer subject14hallWri
    Integer subject15hallWri
    Integer subject16hallWri
    Integer subject17hallWri
    Integer subject18hallWri
    Integer subject19hallWri
    Integer subject20hallWri
    Integer subject21hallWri
    Integer subject22hallWri
    Integer subject23hallWri
    Integer subject24hallWri
    Integer subject25hallWri
    Integer subject26hallWri
    Integer subject27hallWri
    Integer subject28hallWri

    Integer subject0hallObj
    Integer subject1hallObj
    Integer subject2hallObj
    Integer subject3hallObj
    Integer subject4hallObj
    Integer subject5hallObj
    Integer subject6hallObj
    Integer subject7hallObj
    Integer subject8hallObj
    Integer subject9hallObj
    Integer subject10hallObj
    Integer subject11hallObj
    Integer subject12hallObj
    Integer subject13hallObj
    Integer subject14hallObj
    Integer subject15hallObj
    Integer subject16hallObj
    Integer subject17hallObj
    Integer subject18hallObj
    Integer subject19hallObj
    Integer subject20hallObj
    Integer subject21hallObj
    Integer subject22hallObj
    Integer subject23hallObj
    Integer subject24hallObj
    Integer subject25hallObj
    Integer subject26hallObj
    Integer subject27hallObj
    Integer subject28hallObj

    Integer subject0hallPrac
    Integer subject1hallPrac
    Integer subject2hallPrac
    Integer subject3hallPrac
    Integer subject4hallPrac
    Integer subject5hallPrac
    Integer subject6hallPrac
    Integer subject7hallPrac
    Integer subject8hallPrac
    Integer subject9hallPrac
    Integer subject10hallPrac
    Integer subject11hallPrac
    Integer subject12hallPrac
    Integer subject13hallPrac
    Integer subject14hallPrac
    Integer subject15hallPrac
    Integer subject16hallPrac
    Integer subject17hallPrac
    Integer subject18hallPrac
    Integer subject19hallPrac
    Integer subject20hallPrac
    Integer subject21hallPrac
    Integer subject22hallPrac
    Integer subject23hallPrac
    Integer subject24hallPrac
    Integer subject25hallPrac
    Integer subject26hallPrac
    Integer subject27hallPrac
    Integer subject28hallPrac

    Integer subject0hallSba
    Integer subject1hallSba
    Integer subject2hallSba
    Integer subject3hallSba
    Integer subject4hallSba
    Integer subject5hallSba
    Integer subject6hallSba
    Integer subject7hallSba
    Integer subject8hallSba
    Integer subject9hallSba
    Integer subject10hallSba
    Integer subject11hallSba
    Integer subject12hallSba
    Integer subject13hallSba
    Integer subject14hallSba
    Integer subject15hallSba
    Integer subject16hallSba
    Integer subject17hallSba
    Integer subject18hallSba
    Integer subject19hallSba
    Integer subject20hallSba
    Integer subject21hallSba
    Integer subject22hallSba
    Integer subject23hallSba
    Integer subject24hallSba
    Integer subject25hallSba
    Integer subject26hallSba
    Integer subject27hallSba
    Integer subject28hallSba

    Integer subject0hallEff
    Integer subject1hallEff
    Integer subject2hallEff
    Integer subject3hallEff
    Integer subject4hallEff
    Integer subject5hallEff
    Integer subject6hallEff
    Integer subject7hallEff
    Integer subject8hallEff
    Integer subject9hallEff
    Integer subject10hallEff
    Integer subject11hallEff
    Integer subject12hallEff
    Integer subject13hallEff
    Integer subject14hallEff
    Integer subject15hallEff
    Integer subject16hallEff
    Integer subject17hallEff
    Integer subject18hallEff
    Integer subject19hallEff
    Integer subject20hallEff
    Integer subject21hallEff
    Integer subject22hallEff
    Integer subject23hallEff
    Integer subject24hallEff
    Integer subject25hallEff
    Integer subject26hallEff
    Integer subject27hallEff
    Integer subject28hallEff

    Double subject0highest
    Double subject1highest
    Double subject2highest
    Double subject3highest
    Double subject4highest
    Double subject5highest
    Double subject6highest
    Double subject7highest
    Double subject8highest
    Double subject9highest
    Double subject10highest
    Double subject11highest
    Double subject12highest
    Double subject13highest
    Double subject14highest
    Double subject15highest
    Double subject16highest
    Double subject17highest
    Double subject18highest
    Double subject19highest
    Double subject20highest
    Double subject21highest
    Double subject22highest
    Double subject23highest
    Double subject24highest
    Double subject25highest
    Double subject26highest
    Double subject27highest
    Double subject28highest
}
