package com.grailslab.command

/**
 * Created by Hasnat on 6/27/2015.
 */
//@todo-aminul remove this
class ExamScheduleAllCommand {
    Long classSubObjId0
    Integer weightOnResult0
    Integer passMark0
    Integer sortOrder0
    boolean isExtracurricular0
    boolean isCtExam0
    Integer ct1Mark0
    Integer ct2Mark0
    Integer ct3Mark0
    Integer ctEffMark0
    Integer hallMark0
    Integer hallEffMark0
    Boolean isHallPractical0
    Integer hallWrittenMark0
    Integer hallPracticalMark0
    Integer hallObjectiveMark0
    Integer hallSbaMark0
    Integer hallInput50
    Boolean isPassSeparately0
    Integer writtenPassMark0
    Integer practicalPassMark0
    Integer objectivePassMark0
    Integer sbaPassMark0
    Integer input5PassMark0

    Long classSubObjId1
    Integer weightOnResult1
    Integer passMark1
    Integer sortOrder1
    boolean isExtracurricular1
    boolean isCtExam1
    Integer ct1Mark1
    Integer ct2Mark1
    Integer ct3Mark1
    Integer ctEffMark1
    Integer hallMark1
    Integer hallEffMark1
    Boolean isHallPractical1
    Integer hallWrittenMark1
    Integer hallPracticalMark1
    Integer hallObjectiveMark1
    Integer hallSbaMark1
    Integer hallInput51
    Boolean isPassSeparately1
    Integer writtenPassMark1
    Integer practicalPassMark1
    Integer objectivePassMark1
    Integer sbaPassMark1
    Integer input5PassMark1

    Long classSubObjId2
    Integer weightOnResult2
    Integer passMark2
    Integer sortOrder2
    boolean isExtracurricular2
    boolean isCtExam2
    Integer ct1Mark2
    Integer ct2Mark2
    Integer ct3Mark2
    Integer ctEffMark2
    Integer hallMark2
    Integer hallEffMark2
    Boolean isHallPractical2
    Integer hallWrittenMark2
    Integer hallPracticalMark2
    Integer hallObjectiveMark2
    Integer hallSbaMark2
    Integer hallInput52
    Boolean isPassSeparately2
    Integer writtenPassMark2
    Integer practicalPassMark2
    Integer objectivePassMark2
    Integer sbaPassMark2
    Integer input5PassMark2

    Long classSubObjId3
    Integer weightOnResult3
    Integer passMark3
    Integer sortOrder3
    boolean isExtracurricular3
    boolean isCtExam3
    Integer ct1Mark3
    Integer ct2Mark3
    Integer ct3Mark3
    Integer ctEffMark3
    Integer hallMark3
    Integer hallEffMark3
    Boolean isHallPractical3
    Integer hallWrittenMark3
    Integer hallPracticalMark3
    Integer hallObjectiveMark3
    Integer hallSbaMark3
    Integer hallInput53
    Boolean isPassSeparately3
    Integer writtenPassMark3
    Integer practicalPassMark3
    Integer objectivePassMark3
    Integer sbaPassMark3
    Integer input5PassMark3

    Long classSubObjId4
    Integer weightOnResult4
    Integer passMark4
    Integer sortOrder4
    boolean isExtracurricular4
    boolean isCtExam4
    Integer ct1Mark4
    Integer ct2Mark4
    Integer ct3Mark4
    Integer ctEffMark4
    Integer hallMark4
    Integer hallEffMark4
    Boolean isHallPractical4
    Integer hallWrittenMark4
    Integer hallPracticalMark4
    Integer hallObjectiveMark4
    Integer hallSbaMark4
    Integer hallInput54
    Boolean isPassSeparately4
    Integer writtenPassMark4
    Integer practicalPassMark4
    Integer objectivePassMark4
    Integer sbaPassMark4
    Integer input5PassMark4

    Long classSubObjId5
    Integer weightOnResult5
    Integer passMark5
    Integer sortOrder5
    boolean isExtracurricular5
    boolean isCtExam5
    Integer ct1Mark5
    Integer ct2Mark5
    Integer ct3Mark5
    Integer ctEffMark5
    Integer hallMark5
    Integer hallEffMark5
    Boolean isHallPractical5
    Integer hallWrittenMark5
    Integer hallPracticalMark5
    Integer hallObjectiveMark5
    Integer hallSbaMark5
    Integer hallInput55
    Boolean isPassSeparately5
    Integer writtenPassMark5
    Integer practicalPassMark5
    Integer objectivePassMark5
    Integer sbaPassMark5
    Integer input5PassMark5

    Long classSubObjId6
    Integer weightOnResult6
    Integer passMark6
    Integer sortOrder6
    boolean isExtracurricular6
    boolean isCtExam6
    Integer ct1Mark6
    Integer ct2Mark6
    Integer ct3Mark6
    Integer ctEffMark6
    Integer hallMark6
    Integer hallEffMark6
    Boolean isHallPractical6
    Integer hallWrittenMark6
    Integer hallPracticalMark6
    Integer hallObjectiveMark6
    Integer hallSbaMark6
    Integer hallInput56
    Boolean isPassSeparately6
    Integer writtenPassMark6
    Integer practicalPassMark6
    Integer objectivePassMark6
    Integer sbaPassMark6
    Integer input5PassMark6

    Long classSubObjId7
    Integer weightOnResult7
    Integer passMark7
    Integer sortOrder7
    boolean isExtracurricular7
    boolean isCtExam7
    Integer ct1Mark7
    Integer ct2Mark7
    Integer ct3Mark7
    Integer ctEffMark7
    Integer hallMark7
    Integer hallEffMark7
    Boolean isHallPractical7
    Integer hallWrittenMark7
    Integer hallPracticalMark7
    Integer hallObjectiveMark7
    Integer hallSbaMark7
    Integer hallInput57
    Boolean isPassSeparately7
    Integer writtenPassMark7
    Integer practicalPassMark7
    Integer objectivePassMark7
    Integer sbaPassMark7
    Integer input5PassMark7

    Long classSubObjId8
    Integer weightOnResult8
    Integer passMark8
    Integer sortOrder8
    boolean isExtracurricular8
    boolean isCtExam8
    Integer ct1Mark8
    Integer ct2Mark8
    Integer ct3Mark8
    Integer ctEffMark8
    Integer hallMark8
    Integer hallEffMark8
    Boolean isHallPractical8
    Integer hallWrittenMark8
    Integer hallPracticalMark8
    Integer hallObjectiveMark8
    Integer hallSbaMark8
    Integer hallInput58
    Boolean isPassSeparately8
    Integer writtenPassMark8
    Integer practicalPassMark8
    Integer objectivePassMark8
    Integer sbaPassMark8
    Integer input5PassMark8

    Long classSubObjId9
    Integer weightOnResult9
    Integer passMark9
    Integer sortOrder9
    boolean isExtracurricular9
    boolean isCtExam9
    Integer ct1Mark9
    Integer ct2Mark9
    Integer ct3Mark9
    Integer ctEffMark9
    Integer hallMark9
    Integer hallEffMark9
    Boolean isHallPractical9
    Integer hallWrittenMark9
    Integer hallPracticalMark9
    Integer hallObjectiveMark9
    Integer hallSbaMark9
    Integer hallInput59
    Boolean isPassSeparately9
    Integer writtenPassMark9
    Integer practicalPassMark9
    Integer objectivePassMark9
    Integer sbaPassMark9
    Integer input5PassMark9

    Long classSubObjId10
    Integer weightOnResult10
    Integer passMark10
    Integer sortOrder10
    boolean isExtracurricular10
    boolean isCtExam10
    Integer ct1Mark10
    Integer ct2Mark10
    Integer ct3Mark10
    Integer ctEffMark10
    Integer hallMark10
    Integer hallEffMark10
    Boolean isHallPractical10
    Integer hallWrittenMark10
    Integer hallPracticalMark10
    Integer hallObjectiveMark10
    Integer hallSbaMark10
    Integer hallInput510
    Boolean isPassSeparately10
    Integer writtenPassMark10
    Integer practicalPassMark10
    Integer objectivePassMark10
    Integer sbaPassMark10
    Integer input5PassMark10

    Long classSubObjId11
    Integer weightOnResult11
    Integer passMark11
    Integer sortOrder11
    boolean isExtracurricular11
    boolean isCtExam11
    Integer ct1Mark11
    Integer ct2Mark11
    Integer ct3Mark11
    Integer ctEffMark11
    Integer hallMark11
    Integer hallEffMark11
    Boolean isHallPractical11
    Integer hallWrittenMark11
    Integer hallPracticalMark11
    Integer hallObjectiveMark11
    Integer hallSbaMark11
    Integer hallInput511
    Boolean isPassSeparately11
    Integer writtenPassMark11
    Integer practicalPassMark11
    Integer objectivePassMark11
    Integer sbaPassMark11
    Integer input5PassMark11

    Long classSubObjId12
    Integer weightOnResult12
    Integer passMark12
    Integer sortOrder12
    boolean isExtracurricular12
    boolean isCtExam12
    Integer ct1Mark12
    Integer ct2Mark12
    Integer ct3Mark12
    Integer ctEffMark12
    Integer hallMark12
    Integer hallEffMark12
    Boolean isHallPractical12
    Integer hallWrittenMark12
    Integer hallPracticalMark12
    Integer hallObjectiveMark12
    Integer hallSbaMark12
    Integer hallInput512
    Boolean isPassSeparately12
    Integer writtenPassMark12
    Integer practicalPassMark12
    Integer objectivePassMark12
    Integer sbaPassMark12
    Integer input5PassMark12

    Long classSubObjId13
    Integer weightOnResult13
    Integer passMark13
    Integer sortOrder13
    boolean isExtracurricular13
    boolean isCtExam13
    Integer ct1Mark13
    Integer ct2Mark13
    Integer ct3Mark13
    Integer ctEffMark13
    Integer hallMark13
    Integer hallEffMark13
    Boolean isHallPractical13
    Integer hallWrittenMark13
    Integer hallPracticalMark13
    Integer hallObjectiveMark13
    Integer hallSbaMark13
    Integer hallInput513
    Boolean isPassSeparately13
    Integer writtenPassMark13
    Integer practicalPassMark13
    Integer objectivePassMark13
    Integer sbaPassMark13
    Integer input5PassMark13

    Long classSubObjId14
    Integer weightOnResult14
    Integer passMark14
    Integer sortOrder14
    boolean isExtracurricular14
    boolean isCtExam14
    Integer ct1Mark14
    Integer ct2Mark14
    Integer ct3Mark14
    Integer ctEffMark14
    Integer hallMark14
    Integer hallEffMark14
    Boolean isHallPractical14
    Integer hallWrittenMark14
    Integer hallPracticalMark14
    Integer hallObjectiveMark14
    Integer hallSbaMark14
    Integer hallInput514
    Boolean isPassSeparately14
    Integer writtenPassMark14
    Integer practicalPassMark14
    Integer objectivePassMark14
    Integer sbaPassMark14
    Integer input5PassMark14

    Long classSubObjId15
    Integer weightOnResult15
    Integer passMark15
    Integer sortOrder15
    boolean isExtracurricular15
    boolean isCtExam15
    Integer ct1Mark15
    Integer ct2Mark15
    Integer ct3Mark15
    Integer ctEffMark15
    Integer hallMark15
    Integer hallEffMark15
    Boolean isHallPractical15
    Integer hallWrittenMark15
    Integer hallPracticalMark15
    Integer hallObjectiveMark15
    Integer hallSbaMark15
    Integer hallInput515
    Boolean isPassSeparately15
    Integer writtenPassMark15
    Integer practicalPassMark15
    Integer objectivePassMark15
    Integer sbaPassMark15
    Integer input5PassMark15

    Long classSubObjId16
    Integer weightOnResult16
    Integer passMark16
    Integer sortOrder16
    boolean isExtracurricular16
    boolean isCtExam16
    Integer ct1Mark16
    Integer ct2Mark16
    Integer ct3Mark16
    Integer ctEffMark16
    Integer hallMark16
    Integer hallEffMark16
    Boolean isHallPractical16
    Integer hallWrittenMark16
    Integer hallPracticalMark16
    Integer hallObjectiveMark16
    Integer hallSbaMark16
    Integer hallInput516
    Boolean isPassSeparately16
    Integer writtenPassMark16
    Integer practicalPassMark16
    Integer objectivePassMark16
    Integer sbaPassMark16
    Integer input5PassMark16

    Long classSubObjId17
    Integer weightOnResult17
    Integer passMark17
    Integer sortOrder17
    boolean isExtracurricular17
    boolean isCtExam17
    Integer ct1Mark17
    Integer ct2Mark17
    Integer ct3Mark17
    Integer ctEffMark17
    Integer hallMark17
    Integer hallEffMark17
    Boolean isHallPractical17
    Integer hallWrittenMark17
    Integer hallPracticalMark17
    Integer hallObjectiveMark17
    Integer hallSbaMark17
    Integer hallInput517
    Boolean isPassSeparately17
    Integer writtenPassMark17
    Integer practicalPassMark17
    Integer objectivePassMark17
    Integer sbaPassMark17
    Integer input5PassMark17

    Long classSubObjId18
    Integer weightOnResult18
    Integer passMark18
    Integer sortOrder18
    boolean isExtracurricular18
    boolean isCtExam18
    Integer ct1Mark18
    Integer ct2Mark18
    Integer ct3Mark18
    Integer ctEffMark18
    Integer hallMark18
    Integer hallEffMark18
    Boolean isHallPractical18
    Integer hallWrittenMark18
    Integer hallPracticalMark18
    Integer hallObjectiveMark18
    Integer hallSbaMark18
    Integer hallInput518
    Boolean isPassSeparately18
    Integer writtenPassMark18
    Integer practicalPassMark18
    Integer objectivePassMark18
    Integer sbaPassMark18
    Integer input5PassMark18

    Long classSubObjId19
    Integer weightOnResult19
    Integer passMark19
    Integer sortOrder19
    boolean isExtracurricular19
    boolean isCtExam19
    Integer ct1Mark19
    Integer ct2Mark19
    Integer ct3Mark19
    Integer ctEffMark19
    Integer hallMark19
    Integer hallEffMark19
    Boolean isHallPractical19
    Integer hallWrittenMark19
    Integer hallPracticalMark19
    Integer hallObjectiveMark19
    Integer hallSbaMark19
    Integer hallInput519
    Boolean isPassSeparately19
    Integer writtenPassMark19
    Integer practicalPassMark19
    Integer objectivePassMark19
    Integer sbaPassMark19
    Integer input5PassMark19

    Long classSubObjId20
    Integer weightOnResult20
    Integer passMark20
    Integer sortOrder20
    boolean isExtracurricular20
    boolean isCtExam20
    Integer ct1Mark20
    Integer ct2Mark20
    Integer ct3Mark20
    Integer ctEffMark20
    Integer hallMark20
    Integer hallEffMark20
    Boolean isHallPractical20
    Integer hallWrittenMark20
    Integer hallPracticalMark20
    Integer hallObjectiveMark20
    Integer hallSbaMark20
    Integer hallInput520
    Boolean isPassSeparately20
    Integer writtenPassMark20
    Integer practicalPassMark20
    Integer objectivePassMark20
    Integer sbaPassMark20
    Integer input5PassMark20

    Long classSubObjId21
    Integer weightOnResult21
    Integer passMark21
    Integer sortOrder21
    boolean isExtracurricular21
    boolean isCtExam21
    Integer ct1Mark21
    Integer ct2Mark21
    Integer ct3Mark21
    Integer ctEffMark21
    Integer hallMark21
    Integer hallEffMark21
    Boolean isHallPractical21
    Integer hallWrittenMark21
    Integer hallPracticalMark21
    Integer hallObjectiveMark21
    Integer hallSbaMark21
    Integer hallInput521
    Boolean isPassSeparately21
    Integer writtenPassMark21
    Integer practicalPassMark21
    Integer objectivePassMark21
    Integer sbaPassMark21
    Integer input5PassMark21

    Long classSubObjId22
    Integer weightOnResult22
    Integer passMark22
    Integer sortOrder22
    boolean isExtracurricular22
    boolean isCtExam22
    Integer ct1Mark22
    Integer ct2Mark22
    Integer ct3Mark22
    Integer ctEffMark22
    Integer hallMark22
    Integer hallEffMark22
    Boolean isHallPractical22
    Integer hallWrittenMark22
    Integer hallPracticalMark22
    Integer hallObjectiveMark22
    Integer hallSbaMark22
    Integer hallInput522
    Boolean isPassSeparately22
    Integer writtenPassMark22
    Integer practicalPassMark22
    Integer objectivePassMark22
    Integer sbaPassMark22
    Integer input5PassMark22

    Long classSubObjId23
    Integer weightOnResult23
    Integer passMark23
    Integer sortOrder23
    boolean isExtracurricular23
    boolean isCtExam23
    Integer ct1Mark23
    Integer ct2Mark23
    Integer ct3Mark23
    Integer ctEffMark23
    Integer hallMark23
    Integer hallEffMark23
    Boolean isHallPractical23
    Integer hallWrittenMark23
    Integer hallPracticalMark23
    Integer hallObjectiveMark23
    Integer hallSbaMark23
    Integer hallInput523
    Boolean isPassSeparately23
    Integer writtenPassMark23
    Integer practicalPassMark23
    Integer objectivePassMark23
    Integer sbaPassMark23
    Integer input5PassMark23

    Long classSubObjId24
    Integer weightOnResult24
    Integer passMark24
    Integer sortOrder24
    boolean isExtracurricular24
    boolean isCtExam24
    Integer ct1Mark24
    Integer ct2Mark24
    Integer ct3Mark24
    Integer ctEffMark24
    Integer hallMark24
    Integer hallEffMark24
    Boolean isHallPractical24
    Integer hallWrittenMark24
    Integer hallPracticalMark24
    Integer hallObjectiveMark24
    Integer hallSbaMark24
    Integer hallInput524
    Boolean isPassSeparately24
    Integer writtenPassMark24
    Integer practicalPassMark24
    Integer objectivePassMark24
    Integer sbaPassMark24
    Integer input5PassMark24

    Long classSubObjId25
    Integer weightOnResult25
    Integer passMark25
    Integer sortOrder25
    boolean isExtracurricular25
    boolean isCtExam25
    Integer ct1Mark25
    Integer ct2Mark25
    Integer ct3Mark25
    Integer ctEffMark25
    Integer hallMark25
    Integer hallEffMark25
    Boolean isHallPractical25
    Integer hallWrittenMark25
    Integer hallPracticalMark25
    Integer hallObjectiveMark25
    Integer hallSbaMark25
    Integer hallInput525
    Boolean isPassSeparately25
    Integer writtenPassMark25
    Integer practicalPassMark25
    Integer objectivePassMark25
    Integer sbaPassMark25
    Integer input5PassMark25

    Long classSubObjId26
    Integer weightOnResult26
    Integer passMark26
    Integer sortOrder26
    boolean isExtracurricular26
    boolean isCtExam26
    Integer ct1Mark26
    Integer ct2Mark26
    Integer ct3Mark26
    Integer ctEffMark26
    Integer hallMark26
    Integer hallEffMark26
    Boolean isHallPractical26
    Integer hallWrittenMark26
    Integer hallPracticalMark26
    Integer hallObjectiveMark26
    Integer hallSbaMark26
    Integer hallInput526
    Boolean isPassSeparately26
    Integer writtenPassMark26
    Integer practicalPassMark26
    Integer objectivePassMark26
    Integer sbaPassMark26
    Integer input5PassMark26

    Long classSubObjId27
    Integer weightOnResult27
    Integer passMark27
    Integer sortOrder27
    boolean isExtracurricular27
    boolean isCtExam27
    Integer ct1Mark27
    Integer ct2Mark27
    Integer ct3Mark27
    Integer ctEffMark27
    Integer hallMark27
    Integer hallEffMark27
    Boolean isHallPractical27
    Integer hallWrittenMark27
    Integer hallPracticalMark27
    Integer hallObjectiveMark27
    Integer hallSbaMark27
    Integer hallInput527
    Boolean isPassSeparately27
    Integer writtenPassMark27
    Integer practicalPassMark27
    Integer objectivePassMark27
    Integer sbaPassMark27
    Integer input5PassMark27

    Long classSubObjId28
    Integer weightOnResult28
    Integer passMark28
    Integer sortOrder28
    boolean isExtracurricular28
    boolean isCtExam28
    Integer ct1Mark28
    Integer ct2Mark28
    Integer ct3Mark28
    Integer ctEffMark28
    Integer hallMark28
    Integer hallEffMark28
    Boolean isHallPractical28
    Integer hallWrittenMark28
    Integer hallPracticalMark28
    Integer hallObjectiveMark28
    Integer hallSbaMark28
    Integer hallInput528
    Boolean isPassSeparately28
    Integer writtenPassMark28
    Integer practicalPassMark28
    Integer objectivePassMark28
    Integer sbaPassMark28
    Integer input5PassMark28

    Long classSubObjId29
    Integer weightOnResult29
    Integer passMark29
    Integer sortOrder29
    boolean isExtracurricular29
    boolean isCtExam29
    Integer ct1Mark29
    Integer ct2Mark29
    Integer ct3Mark29
    Integer ctEffMark29
    Integer hallMark29
    Integer hallEffMark29
    Boolean isHallPractical29
    Integer hallWrittenMark29
    Integer hallPracticalMark29
    Integer hallObjectiveMark29
    Integer hallSbaMark29
    Integer hallInput529
    Boolean isPassSeparately29
    Integer writtenPassMark29
    Integer practicalPassMark29
    Integer objectivePassMark29
    Integer sbaPassMark29
    Integer input5PassMark29

    Long classSubObjId30
    Integer weightOnResult30
    Integer passMark30
    Integer sortOrder30
    boolean isExtracurricular30
    boolean isCtExam30
    Integer ct1Mark30
    Integer ct2Mark30
    Integer ct3Mark30
    Integer ctEffMark30
    Integer hallMark30
    Integer hallEffMark30
    Boolean isHallPractical30
    Integer hallWrittenMark30
    Integer hallPracticalMark30
    Integer hallObjectiveMark30
    Integer hallSbaMark30
    Integer hallInput530
    Boolean isPassSeparately30
    Integer writtenPassMark30
    Integer practicalPassMark30
    Integer objectivePassMark30
    Integer sbaPassMark30
    Integer input5PassMark30

    Long classSubObjId31
    Integer weightOnResult31
    Integer passMark31
    Integer sortOrder31
    boolean isExtracurricular31
    boolean isCtExam31
    Integer ct1Mark31
    Integer ct2Mark31
    Integer ct3Mark31
    Integer ctEffMark31
    Integer hallMark31
    Integer hallEffMark31
    Boolean isHallPractical31
    Integer hallWrittenMark31
    Integer hallPracticalMark31
    Integer hallObjectiveMark31
    Integer hallSbaMark31
    Integer hallInput531
    Boolean isPassSeparately31
    Integer writtenPassMark31
    Integer practicalPassMark31
    Integer objectivePassMark31
    Integer sbaPassMark31
    Integer input5PassMark31

    Long classSubObjId32
    Integer weightOnResult32
    Integer passMark32
    Integer sortOrder32
    boolean isExtracurricular32
    boolean isCtExam32
    Integer ct1Mark32
    Integer ct2Mark32
    Integer ct3Mark32
    Integer ctEffMark32
    Integer hallMark32
    Integer hallEffMark32
    Boolean isHallPractical32
    Integer hallWrittenMark32
    Integer hallPracticalMark32
    Integer hallObjectiveMark32
    Integer hallSbaMark32
    Integer hallInput532
    Boolean isPassSeparately32
    Integer writtenPassMark32
    Integer practicalPassMark32
    Integer objectivePassMark32
    Integer sbaPassMark32
    Integer input5PassMark32

    Long classSubObjId33
    Integer weightOnResult33
    Integer passMark33
    Integer sortOrder33
    boolean isExtracurricular33
    boolean isCtExam33
    Integer ct1Mark33
    Integer ct2Mark33
    Integer ct3Mark33
    Integer ctEffMark33
    Integer hallMark33
    Integer hallEffMark33
    Boolean isHallPractical33
    Integer hallWrittenMark33
    Integer hallPracticalMark33
    Integer hallObjectiveMark33
    Integer hallSbaMark33
    Integer hallInput533
    Boolean isPassSeparately33
    Integer writtenPassMark33
    Integer practicalPassMark33
    Integer objectivePassMark33
    Integer sbaPassMark33
    Integer input5PassMark33

    Long classSubObjId34
    Integer weightOnResult34
    Integer passMark34
    Integer sortOrder34
    boolean isExtracurricular34
    boolean isCtExam34
    Integer ct1Mark34
    Integer ct2Mark34
    Integer ct3Mark34
    Integer ctEffMark34
    Integer hallMark34
    Integer hallEffMark34
    Boolean isHallPractical34
    Integer hallWrittenMark34
    Integer hallPracticalMark34
    Integer hallObjectiveMark34
    Integer hallSbaMark34
    Integer hallInput534
    Boolean isPassSeparately34
    Integer writtenPassMark34
    Integer practicalPassMark34
    Integer objectivePassMark34
    Integer sbaPassMark34
    Integer input5PassMark34

    Long classSubObjId35
    Integer weightOnResult35
    Integer passMark35
    Integer sortOrder35
    boolean isExtracurricular35
    boolean isCtExam35
    Integer ct1Mark35
    Integer ct2Mark35
    Integer ct3Mark35
    Integer ctEffMark35
    Integer hallMark35
    Integer hallEffMark35
    Boolean isHallPractical35
    Integer hallWrittenMark35
    Integer hallPracticalMark35
    Integer hallObjectiveMark35
    Integer hallSbaMark35
    Integer hallInput535
    Boolean isPassSeparately35
    Integer writtenPassMark35
    Integer practicalPassMark35
    Integer objectivePassMark35
    Integer sbaPassMark35
    Integer input5PassMark35

    Long classSubObjId36
    Integer weightOnResult36
    Integer passMark36
    Integer sortOrder36
    boolean isExtracurricular36
    boolean isCtExam36
    Integer ct1Mark36
    Integer ct2Mark36
    Integer ct3Mark36
    Integer ctEffMark36
    Integer hallMark36
    Integer hallEffMark36
    Boolean isHallPractical36
    Integer hallWrittenMark36
    Integer hallPracticalMark36
    Integer hallObjectiveMark36
    Integer hallSbaMark36
    Integer hallInput536
    Boolean isPassSeparately36
    Integer writtenPassMark36
    Integer practicalPassMark36
    Integer objectivePassMark36
    Integer sbaPassMark36
    Integer input5PassMark36

    Long classSubObjId37
    Integer weightOnResult37
    Integer passMark37
    Integer sortOrder37
    boolean isExtracurricular37
    boolean isCtExam37
    Integer ct1Mark37
    Integer ct2Mark37
    Integer ct3Mark37
    Integer ctEffMark37
    Integer hallMark37
    Integer hallEffMark37
    Boolean isHallPractical37
    Integer hallWrittenMark37
    Integer hallPracticalMark37
    Integer hallObjectiveMark37
    Integer hallSbaMark37
    Integer hallInput537
    Boolean isPassSeparately37
    Integer writtenPassMark37
    Integer practicalPassMark37
    Integer objectivePassMark37
    Integer sbaPassMark37
    Integer input5PassMark37

    Long classSubObjId38
    Integer weightOnResult38
    Integer passMark38
    Integer sortOrder38
    boolean isExtracurricular38
    boolean isCtExam38
    Integer ct1Mark38
    Integer ct2Mark38
    Integer ct3Mark38
    Integer ctEffMark38
    Integer hallMark38
    Integer hallEffMark38
    Boolean isHallPractical38
    Integer hallWrittenMark38
    Integer hallPracticalMark38
    Integer hallObjectiveMark38
    Integer hallSbaMark38
    Integer hallInput538
    Boolean isPassSeparately38
    Integer writtenPassMark38
    Integer practicalPassMark38
    Integer objectivePassMark38
    Integer sbaPassMark38
    Integer input5PassMark38

    Long classSubObjId39
    Integer weightOnResult39
    Integer passMark39
    Integer sortOrder39
    boolean isExtracurricular39
    boolean isCtExam39
    Integer ct1Mark39
    Integer ct2Mark39
    Integer ct3Mark39
    Integer ctEffMark39
    Integer hallMark39
    Integer hallEffMark39
    Boolean isHallPractical39
    Integer hallWrittenMark39
    Integer hallPracticalMark39
    Integer hallObjectiveMark39
    Integer hallSbaMark39
    Integer hallInput539
    Boolean isPassSeparately39
    Integer writtenPassMark39
    Integer practicalPassMark39
    Integer objectivePassMark39
    Integer sbaPassMark39
    Integer input5PassMark39
}
